INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (1, 'Abyssinian','Unspecified but somewhere in AfroAsia likely Ethiopia', 'Natural', 'Semiforeign', 'Short', 'Ticked tabby' ,'https://upload.wikimedia.org/wikipedia/commons/9/9b/Gustav_chocolate.jpg')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (2, 'Aegean','Greece', 'Natural', 'Moderate', 'Semilong', 'Multicolor' ,'https://upload.wikimedia.org/wikipedia/commons/5/51/Aegean_cat.jpg')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (3, 'American Bobtail','the United States', 'Mutation', 'Cobby', 'Semilong', 'All' ,'https://upload.wikimedia.org/wikipedia/commons/8/88/American_bobtail_2.jpg')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (4, 'American Curl','the United States', 'Mutation', 'Semiforeign', 'Semilong', 'All' ,'https://upload.wikimedia.org/wikipedia/commons/1/17/American_curl_2.jpg')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (5, 'American Ringtail','the United States', 'Mutation', 'Foreign', 'Semilong', 'All' ,'https://upload.wikimedia.org/wikipedia/commons/a/a8/Chunky_Monkey_American_Ringtail_Cat_3rd_Generation.jpg')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (6, 'American Shorthair','the United States', 'Natural', 'Cobby', 'Short', 'All' ,'https://upload.wikimedia.org/wikipedia/commons/0/0c/American_Shorthair.jpg')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (7, 'American Wirehair','the United States', 'Mutation', 'Normal', 'Rex', 'All' ,'https://upload.wikimedia.org/wikipedia/commons/7/7f/American_Wirehair_-_CFF_cat_show_Heinola_2008-05-04_IMG_8721.JPG')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (8, 'Aphrodite Giant','Cyprus', 'Natural', 'Lean and muscular', 'All', 'All' ,'https://upload.wikimedia.org/wikipedia/commons/f/f5/Aphrodite''s_Giant.jpg')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (9, 'Arabian Mau','the Arabian Peninsula', 'Natural', 'Moderate and muscular', 'Short', 'All' ,'https://upload.wikimedia.org/wikipedia/commons/5/53/3yoArabianMau.jpeg')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (10, 'Asian','Developed in the United Kingdom
foundation stock from Asia', 'Natural', 'Moderate', 'Short', 'Evenly solid' ,'https://upload.wikimedia.org/wikipedia/commons/a/a1/BrownVarientAsianCat.JPG')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (11, 'Asian Semilonghair','the United Kingdom', 'Crossbreed between the Burmese and longhaired cats', 'Cobby', 'Semilong', 'Evenly solid' ,'https://upload.wikimedia.org/wikipedia/commons/a/a7/Tiffanie_at_cat_show.jpg')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (12, 'Australian Mist','Australia', 'Crossbreed between the Abyssinian and Burmese', 'Moderate', 'Short', 'Spotted or marbled' ,'https://upload.wikimedia.org/wikipedia/commons/f/f0/Australian_Mist.jpg')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (13, 'Balinese','Developed in the United States
foundation stock from Thailand', 'Mutation of the Siamese', 'Semiforeign', 'Long', 'Colorpoint' ,'https://upload.wikimedia.org/wikipedia/commons/e/e6/Oskar.jpg')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (14, 'Bambino','the United States', 'Crossbreed between the Munchkin and Sphynx', 'Dwarf', 'Rex', '', '../otabby.jpeg')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (15, 'Bengal','Developed in the United States
but created in Asia', 'Hybrid of the Abyssinian and Egyptian Mau  leopard cat Prionailurus bengalensis', 'Large', 'Short', 'Spotted marbled or rosetted' ,'https://upload.wikimedia.org/wikipedia/commons/d/df/Bengal_Cat_%28Fia%29.jpg')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (16, 'Birman','Developed in France
foundation stock from Burma Myanmar', 'The original Birman was crossed with the Siamese and the Persian to create the Birman of today', 'Cobby', 'Semilong', 'Mitted colorpoint' ,'https://upload.wikimedia.org/wikipedia/commons/a/ac/Birman2.jpg')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (17, 'Bombay','the United States and Burma Myanmar', 'Crossbreed between the Black American Shorthair and Sable Burmese', 'Cobby', 'Short', 'Solid black' ,'https://upload.wikimedia.org/wikipedia/commons/a/ac/Bombay_femelle.JPG')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (18, 'Brazilian Shorthair','Brazil', 'Natural', 'Normal', 'Short', 'All' ,'https://upload.wikimedia.org/wikipedia/commons/8/87/Gato_pelo_curto_brasileiro.JPG')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (19, 'British Longhair','the United Kingdom England', 'Natural', 'Cobby', 'Semilong', 'All' ,'https://upload.wikimedia.org/wikipedia/commons/5/50/British_Longhair_-_Black_Silver_Shaded.jpg')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (20, 'British Shorthair','the United Kingdom England', 'Natural', 'Cobby', 'Short', 'All' ,'https://upload.wikimedia.org/wikipedia/commons/9/9d/Britishblue.jpg')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (21, 'Burmese','Burma Myanmar', 'Natural', 'Semiforeign or semicobby', 'Short', 'Solid or tortoiseshell' ,'https://upload.wikimedia.org/wikipedia/commons/0/0c/Male_Chocolate_Burmese_Cat.jpg')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (22, 'Burmilla','the United Kingdom England', 'Crossbreed between the Brown Tortie Burmese and the Chinchilla Persian', 'Semicobby', 'Short', 'Solid with Shaded Silver and Silver Tipped patterns' ,'https://upload.wikimedia.org/wikipedia/commons/e/e9/Male_Burmilla_cat.jpeg')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (23, 'California Spangled','the United States', 'Crossbreed between the Abyssinian American Shorthair and British Shorthair', 'Moderate', 'Short', 'Spotted tabby' ,'https://upload.wikimedia.org/wikipedia/commons/6/6c/Star_Spangled_Cat.jpg')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (24, 'ChantillyTiffany','the United States', 'Natural', 'Cobby', 'Long', 'Solid classic tabby spotted tabby and ticked tabby' ,'https://upload.wikimedia.org/wikipedia/commons/5/5f/Tiffany3.jpg')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (25, 'Chartreux','France', 'Natural', 'Muscular cobby', 'Short', 'Varying shades of blue' ,'https://upload.wikimedia.org/wikipedia/commons/7/7f/Abbaye_fev2006_003.jpg')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (26, 'Chausie','the United States', 'Hybrid of the Abyssinian  jungle cat Felis chaus', 'Normal', 'Short', 'Solid black black grizzled tabby and black ticked tabby' ,'https://upload.wikimedia.org/wikipedia/commons/6/61/Chausiecatexample.jpg')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (27, 'Colorpoint Shorthair','the United Kingdom England', 'Crossbreed between the Abyssinian Siamese and shorthaired cats', 'Foreign', 'Short', 'Colorpoint' ,'https://upload.wikimedia.org/wikipedia/en/d/d5/Jake117.jpg')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (28, 'Cornish Rex','Cornwall England
the United Kingdom', 'Mutation', 'Foreign', 'Rex', 'All' ,'https://upload.wikimedia.org/wikipedia/commons/b/b8/BebopsLilacPrince.JPG')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (29, 'Cymric Manx Longhair or Longhaired Manxa','the Isle of Man the United States and Canada b', 'Mutation of the Manx', 'Semicobby', 'Long', 'All' ,'https://upload.wikimedia.org/wikipedia/commons/e/e4/Cymric_-_Norwegian_forest_cat_presentation_show_Kotka_2009-02-01_IMG_0687.JPG')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (30, 'Cyprus','Cyprus', 'Natural', 'Lean and muscular', 'All', 'All' ,'https://upload.wikimedia.org/wikipedia/commons/b/b9/CyprusShorthair.jpg')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (31, 'Devon Rex','Buckfastleigh Devon England the United Kingdom', 'Mutation', 'Semiforeign', 'Rex', 'All' ,'https://upload.wikimedia.org/wikipedia/commons/b/b0/Devon_Rex_Izzy.jpg')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (32, 'Donskoy or
Don Sphynx','Russia', 'Mutation', 'Semiforeign', 'Hairless', 'Solid' ,'https://upload.wikimedia.org/wikipedia/commons/2/21/Cat_don_sphinx.JPG')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (33, 'Dragon Li or
Chinese Li Hua','China', 'Natural', 'Normal', 'Short', 'Ticked tabby' ,'https://upload.wikimedia.org/wikipedia/commons/c/c2/Dragon_Li_-_Li_Hua_Mau1.jpg')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (34, 'Dwelf','the United States', 'Crossbreed between the American Curl Munchkin and Sphynx', 'Dwarf', 'Hairless', 'All', '../otabby.jpeg')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (35, 'Egyptian Mau','Egypt', 'Natural', 'Moderate and muscular', 'Short', 'Spotted tabby' ,'https://upload.wikimedia.org/wikipedia/commons/e/e1/Egy_mau.jpg')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (36, 'European Shorthair','Continental Europe', 'Natural', 'Moderate', 'Short', 'All' ,'https://upload.wikimedia.org/wikipedia/commons/5/5d/European_shorthair_procumbent_Quincy.jpg')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (37, 'Exotic Shorthair','the United States', 'Crossbreed between the American Shorthair and Persian', 'Cobby', 'Short', 'All' ,'https://upload.wikimedia.org/wikipedia/commons/4/4f/Cream_tabby_exotic_cat.jpg')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (38, 'Foldex','Canada', 'Crossbreed between the Exotic Shorthair and Scottish Fold', 'Cobby', 'Short', 'All' ,'https://upload.wikimedia.org/wikipedia/commons/2/2c/Cachorro_de_Gato_FoldEx_%28%22Belisario_del_Laberinto%22%29.JPG')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (39, 'German Rex','Germany', 'Mutation', 'Semiforeign', 'Rex', 'All' ,'https://upload.wikimedia.org/wikipedia/commons/f/ff/German_Rex_Emi.jpg')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (40, 'Havana Brown','the United Kingdom England
foundation stock from Thailand', 'Crossbreed between the Siamese and black shorthaired cats', 'Semiforeign', 'Short', 'Solid brown' ,'https://upload.wikimedia.org/wikipedia/commons/5/5d/Havana_Brown.jpg')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (41, 'Highlander','the United States', 'Crossbreed between the Desert Lynx and Jungle Curl', 'Moderate', 'Shortlong', 'All' ,'https://upload.wikimedia.org/wikipedia/commons/1/15/Highlander-7.jpg')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (42, 'Himalayan or
Colorpoint Persianc','the United States and the United Kingdom', 'Crossbreed between the Persian and Siamese', 'Cobby', 'Long', 'Colorpoint' ,'https://upload.wikimedia.org/wikipedia/commons/d/dc/Chocolate_Himlayan.jpg')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (43, 'Japanese Bobtail','Japand', 'Mutation', 'Moderate', 'Shortlong', 'All' ,'https://upload.wikimedia.org/wikipedia/commons/5/56/JapaneseBobtailBlueEyedMi-ke.JPG')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (44, 'Javanese or
Colorpoint Longhaire','Developed in the United States and Canada
foundation stock from Southeast Asia', 'Crossbreed between the Balinese with some Colorpoint Shorthair Oriental Longhair and Siamese', 'Oriental', 'Long', 'Colorpoint' ,'https://upload.wikimedia.org/wikipedia/commons/6/6f/Javanese_cat.jpg')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (46, 'Khao Manee','Thailand', 'Natural', 'Moderate', 'Short', 'Solid white' ,'https://upload.wikimedia.org/wikipedia/commons/9/98/Khao_Manee_%22ChaWee%22.jpg')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (47, 'Kinkalow','the United States', 'Crossbreed between the Munchkin and American Curl', 'Dwarf', 'Short', 'All' ,'https://upload.wikimedia.org/wikipedia/commons/f/fa/Tinkerbella.jpg')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (48, 'Korat','Thailand', 'Natural', 'Semiforeign or semicobby and muscular', 'Short', 'Solid blue' ,'https://upload.wikimedia.org/wikipedia/commons/c/c1/Veda%2Cchat-adulte-m%C3%A2le-race-korat.JPG')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (49, 'Korean Bobtail','Korea', 'Natural mutation', 'Moderate', 'Shortlong', 'Colorpoint' ,'https://upload.wikimedia.org/wikipedia/commons/d/d4/Japanese_Bobtail_walking.JPG')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (50, 'Korn Ja','Thailand', 'Natural', 'Small', 'Short', 'Solid black', '../otabby.jpeg')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (51, 'Kurilian Bobtail or
Kuril Islands Bobtail','Eastern Russia and Japan', 'Natural mutation', 'Semicobby', 'Shortlong', 'All' ,'https://upload.wikimedia.org/wikipedia/commons/8/82/Kurilian_bobtail.JPG')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (52, 'Lambkin','the United States', 'Crossbreed between the Munchkin and Selkirk Rex', 'Dwarf', 'Rex', 'All', '../otabby.jpeg')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (53, 'LaPerm','the United States', 'Mutation', 'Moderate', 'Rex', 'All' ,'https://upload.wikimedia.org/wikipedia/commons/a/ac/Laperm_LH_red_tabby.jpg')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (54, 'Lykoi','the United States', 'Mutation', 'Moderate', 'Hairless', 'Solid black roan' ,'https://upload.wikimedia.org/wikipedia/commons/1/1e/8-month-old_male_Lykoi.jpg')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (55, 'Maine Coon','the United States', 'Natural crossbreed', 'Large', 'Semilonglong', 'All' ,'https://upload.wikimedia.org/wikipedia/commons/d/d0/Maine_Coon_female.jpg')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (56, 'Manx','the Isle of Man', 'Mutation', 'Moderate', 'Shortlong', 'All' ,'https://upload.wikimedia.org/wikipedia/commons/e/e3/Japanese_Bobtail_looking_like_Manx.jpg')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (57, 'Mekong Bobtail','Russia', 'Mutation', 'Moderate', 'Short', 'Colorpoint' ,'https://upload.wikimedia.org/wikipedia/commons/9/94/Mekong_bobtail_female%2C_Cofein_Pride_cattery.jpg')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (58, 'Minskin','the United States', 'Crossbreed between the Munchkin Burmese Devon Rex and Sphynx', 'Dwarf', 'Hairless', 'All' ,'https://upload.wikimedia.org/wikipedia/commons/7/73/Minskin_Kitten_Female_blue_tabby_color-pattern.jpg')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (59, 'Minuet','the United States', 'Crossbreed between the Persian and Munchkin', 'Dwarf', 'Shortlong', 'All' ,'https://upload.wikimedia.org/wikipedia/commons/5/54/White_Gray_Minuet_Cat.png')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (60, 'Munchkin','the United States', 'Mutation', 'Dwarf', 'Shortlong', 'All' ,'https://upload.wikimedia.org/wikipedia/commons/6/6e/Longhairedmunchkin.jpg')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (61, 'Nebelung','the United States', 'Natural mutation', 'Foreign', 'Semilong', 'Solid blue' ,'https://upload.wikimedia.org/wikipedia/commons/9/9e/Nebelung_Male%2C_Aleksandr_van_Song_de_Chine.JPG')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (62, 'Norwegian Forest Cat','Norway', 'Natural', 'Cobby', 'Long', 'All but colorpoint' ,'https://upload.wikimedia.org/wikipedia/commons/6/6e/Norskskogkatt_Evita_3.JPG')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (63, 'Ocicat','the United States', 'Crossbreed between the Abyssinian American Shorthair and Siamese', 'Large', 'Short', 'Spotted tabby' ,'https://upload.wikimedia.org/wikipedia/commons/2/21/Ocicat-Charan.jpg')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (64, 'Ojos Azules','the United States', 'Crossbreed', 'Moderate', 'Short', 'All' ,'https://upload.wikimedia.org/wikipedia/commons/4/42/Lazuli01.jpg')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (65, 'Oregon Rex
extinct','the United States', 'Mutation', '', 'Rex', '', '../otabby.jpeg')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (66, 'Oriental Bicolor','Developed in the United States and the United Kingdom later in Continental Europe
foundation stock ultimately from Thailand', 'Color variety of the Oriental Shorthair', 'Oriental', 'Short', 'Bicolor' ,'https://upload.wikimedia.org/wikipedia/commons/6/6a/Oriental_shorthair_20070130_caroline.jpg')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (67, 'Oriental Longhairf','Developed in the United States and the United Kingdom
foundation stock ultimately from Thailand', 'Crossbreed between the Oriental Shorthair and longhaired cats', 'Oriental', 'Semilong', 'All if colorpoint is considered to be a separate breed it is called the Javanese' ,'https://upload.wikimedia.org/wikipedia/commons/6/65/OLH-GIP_Divan_Cesar.jpg')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (68, 'Oriental Shorthairf','Developed in the United States and the United Kingdom
foundation stock ultimately from Thailand', 'Crossbreed between the European Shorthair and Siamese', 'Oriental', 'Short', 'All' ,'https://upload.wikimedia.org/wikipedia/commons/9/91/Oriental_Shorthair_Blue_Eyed_White_cat_%28juvenile%29.jpg')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (69, 'Persian modern','Developed in the United States and Europe
foundation stock from Greater Iran', 'Mutation of the Traditional Persian', 'Cobby', 'Long', 'All but colorpoint' ,'https://upload.wikimedia.org/wikipedia/commons/8/81/Persialainen.jpg')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (70, 'Persian traditional','Greater Iran', 'Natural but some crossbreeding with the Turkish Angora', 'Cobby', 'Long', 'All but colorpoint' ,'https://upload.wikimedia.org/wikipedia/commons/6/67/SnowyandHazy.jpg')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (71, 'Peterbald','Russia', 'Crossbreed between the Donskoy Oriental Shorthair and Siamese
before this it was between the Balinese and Javanese', 'Oriental', 'Hairless velour brush or straight coat', 'All' ,'https://upload.wikimedia.org/wikipedia/commons/b/b7/Tamila_the_lilac_tabby_Peterbald_cat.jpg')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (72, 'Pixiebob','the United States', 'Mutation falsely claimed to be a hybrid of the domestic cat and the bobcat Lynx rufus early on', 'Medium', 'Short', 'Spotted tabby' ,'https://upload.wikimedia.org/wikipedia/commons/8/8c/Jarnac_Bepacific_feb07.jpg')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (73, 'Ragamuffin or
Liebling obsolete','the United States', 'Crossbreed between the Ragdoll with limited outcrossing to the Himalayan the Persian and other longhaired cats', 'Cobby', 'Long', 'All' ,'https://upload.wikimedia.org/wikipedia/commons/f/f3/20050922AmarilloRes.jpg')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (74, 'Ragdoll','the United States', 'Behavioral mutation in a crossbreed presumed to be between the Persian or Turkish Angora and the Birman or Burmese', 'Cobby', 'Long', 'Colorpoint mitted or bicolor' ,'https://upload.wikimedia.org/wikipedia/commons/6/64/Ragdoll_from_Gatil_Ragbelas.jpg')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (75, 'Raas','Raas Island Indonesia', 'Natural', 'Moderate', 'Short', 'Solid blue solid cinnamon or cinnamon colorpoint' ,'https://upload.wikimedia.org/wikipedia/commons/3/31/Kucing_Busok_Jantan.jpg')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (76, 'Russian Blue','Russia', 'Natural', 'Moderate Oriental', 'Short', 'Solid blue' ,'https://upload.wikimedia.org/wikipedia/commons/5/5f/Russian_Blue_001.gif')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (77, 'Russian White Russian Black and Russian Tabby','Developed in Australia
foundation stock from Russia', 'Crossbreeds between the Russian Blue and shorthaired cats from Siberia Russia', 'Moderate', 'Short', 'Solid white solid black and tabby', '../otabby.jpeg')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (78, 'Sam Sawet','Thailand', 'Color variety of the Thai', 'Moderate', 'Short', 'Solid', '../otabby.jpeg')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (79, 'Savannah','the United States', 'Hybrid of the domestic cat x serval Leptailurus serval', 'Large', 'Short', 'Spotted' ,'https://upload.wikimedia.org/wikipedia/commons/c/c4/Savannah_Cat_portrait.jpg')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (80, 'Scottish Fold','the United Kingdom Scotland', 'Mutation of the bones and cartilage of the ears', 'Cobby', 'Shortlong', 'All' ,'https://upload.wikimedia.org/wikipedia/commons/8/83/Lilac_Scottish_Fold.jpg')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (81, 'Selkirk Rex','the United States in ', 'Mutationcrossbreed between the American Shorthair Persian Himalayan Exotic Shorthair and British Shorthair', 'Large and cobby', 'Shortlong longhair sometimes in early generations can appear to be semilong', 'All' ,'https://upload.wikimedia.org/wikipedia/en/c/c3/PolloSelkirkRex.jpg')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (82, 'Serengeti','the United States', 'Crossbreedhybrid between the Bengal and Oriental Shorthair', 'Oriental', 'Short', 'Spotted' ,'https://upload.wikimedia.org/wikipedia/commons/1/1a/Serengetimalecat.jpg')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (83, 'Serrade Petit','France', 'Natural', 'Semicobby', 'Short', 'Solid tan solid orange and solid white' ,'https://upload.wikimedia.org/wikipedia/commons/c/c7/Serrade_petit.jpg')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (84, 'Siamese modern
for traditional see Thai below','Developed in the United States and Europe
foundation stock from Thailand', 'Mutation of the Thai', 'Oriental', 'Short', 'Colorpoint' ,'https://upload.wikimedia.org/wikipedia/commons/2/25/Siam_lilacpoint.jpg')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (85, 'Siberian or
Siberian Forest Cat
Neva Masquerade colorpoint variety','Russia Ukraine', 'Natural', 'Semicobby', 'Semilong', 'All except chocolate lilac cinnamon and fawn' ,'https://upload.wikimedia.org/wikipedia/commons/4/42/Siberiancat.jpg')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (86, 'Singapura','Developed in the United States
foundation stock from Singapore', 'Possibly a mutation of a crossbreed excluding the Munchkin solving why they are so small', 'Small', 'Short', 'Ticked tabby' ,'https://upload.wikimedia.org/wikipedia/commons/d/da/Raffles_singapura_cat.jpg')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (87, 'Snowshoe','the United States', 'Crossbreed between the American Shorthair and Siamese', 'Moderate', 'Short', 'Mitted colorpoint' ,'https://upload.wikimedia.org/wikipedia/commons/4/4b/Snowshoe_%28cat%29.JPG')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (88, 'Sokoke','Kenya', 'Natural', 'Moderate', 'Short', 'Ticked tabby' ,'https://upload.wikimedia.org/wikipedia/commons/9/94/Sokoke_dalili.jpg')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (89, 'Somali','the United States Canada', 'Mutation', 'Cobby', 'Long', 'Ticked tabby' ,'https://upload.wikimedia.org/wikipedia/commons/c/c6/Blue_Somali_kitten_age_3_months.jpg')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (90, 'Sphynx','Canada Europe', 'Mutation', 'Oriental', 'Hairless', 'All' ,'https://upload.wikimedia.org/wikipedia/commons/e/e8/Sphinx2_July_2006.jpg')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (91, 'Suphalak','Thailand', 'Natural', 'Moderate', 'Short', 'Solid reddishbrown' ,'https://upload.wikimedia.org/wikipedia/commons/5/52/Suphalak_Female_in_Thailand_named_AumDaengManee.jpg')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (92, 'Thai or
Traditional Classic or Oldstyle Siamese
Wichien Maatg','Thailand', 'Natural', 'Moderate', 'Short', 'Colorpoint' ,'https://upload.wikimedia.org/wikipedia/commons/5/57/Mimbi3.JPG')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (93, 'Thai Lilac Thai Blue Point and Thai Lilac Point','Thailand', 'Color varieties of the Korat', 'Moderate', 'Short', 'Solid lilac and colorpoint blue point and lilac point only' ,'https://upload.wikimedia.org/wikipedia/commons/4/45/Thai_Lilac.jpg')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (94, 'Tonkinese','Canada the United States', 'Crossbreed between the Burmese and Siamese', 'Oriental', 'Short', 'Colorpoint mink or solid' ,'https://upload.wikimedia.org/wikipedia/commons/8/81/Tonkinese.gif')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (95, 'Toybob','Russia', 'Mutation', 'Dwarf', 'Short', 'All', '../otabby.jpeg')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (96, 'Toyger','the United States', 'Crossbreedhybrid between the Bengal and shorthaired cats', 'Moderate', 'Short', 'Mackerel tabby' ,'https://upload.wikimedia.org/wikipedia/commons/c/ca/Toyger_-_Cornish_Rex_presentation_show_Riihim%C3%A4ki_2008-11-16_IMG_0101.JPG')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (97, 'Turkish Angora','Turkey', 'Natural', 'Semicobby', 'Semilong', 'All' ,'https://upload.wikimedia.org/wikipedia/commons/a/a1/Turkse_angora.jpg')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (98, 'Turkish Van','Developed in the United Kingdom England
foundation stock from Turkey', 'Natural', 'Semicobby', 'Semilong', 'Van pattern' ,'https://upload.wikimedia.org/wikipedia/commons/1/11/Turkish_Van_Example2.jpg')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (99, 'Turkish Vankedisi','Turkey', 'Natural', 'Svelte', 'Long', 'Solid white' ,'https://upload.wikimedia.org/wikipedia/commons/f/fb/Van_Cat_2_2015.JPG')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (100, 'Ukrainian Levkoy','Ukraine', 'Crossbreed between the Donskoy and Scottish Fold', 'Moderate', 'Hairless', 'Solid gray' ,'https://upload.wikimedia.org/wikipedia/commons/9/92/Ukrainian_Levkoy_cat.jpg')
INSERT INTO cat (id, breed, location, breed_type, body_type, coat_type, coat_pattern, image_location) VALUES (101, 'York Chocolate','New York the United States', 'Natural', 'Moderate', 'Long', 'Solid chocolate solid lilac and solid taupe or any of these colors with white' ,'https://upload.wikimedia.org/wikipedia/commons/2/26/York_Chocolate.jpg')